package sudark2.Sudark.equipmentPro.EffectBasic;

import org.bukkit.Material;
import org.bukkit.util.Transformation;
import org.joml.Quaternionf;
import org.joml.Vector3f;

public class EquipmentDisplay {

    static float p = 0.125f;
    static float hp = 0.07f;

    public static Effect[] getEffect(String style) throws NoSuchFieldException, IllegalAccessException {
        return (Effect[]) EquipmentDisplay.class.getDeclaredField(style).get(null);
    }

    static Effect[] obsidian = {
            new Effect(Material.OBSIDIAN, asl(1, 4, 0, 1, 1, 1, p), p),
            new Effect(Material.CRYING_OBSIDIAN, asl(1, 5, 0, 1, 2, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(2, 6, -1, 1, 3, 1, p), p),
            new Effect(Material.CRYING_OBSIDIAN, asl(2, 9, -2, 2, 1, 1, p), p),
            new Effect(Material.CRYING_OBSIDIAN, asl(1, 8, -1, 1, 1, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(-2, 4, 0, 1, 1, 1, p), p),
            new Effect(Material.CRYING_OBSIDIAN, asl(-2, 5, 0, 1, 2, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(-3, 6, -1, 1, 3, 1, p), p),
            new Effect(Material.CRYING_OBSIDIAN, asl(-4, 9, -2, 2, 1, 1, p), p),
            new Effect(Material.CRYING_OBSIDIAN, asl(-2, 8, -1, 1, 1, 1, p), p),
    };

    static Effect[] wild = {
            new Effect(Material.BROWN_TERRACOTTA, asl(1, 4, 0, 1, 2, 1, p), p),
            new Effect(Material.BROWN_TERRACOTTA, asl(2, 5, -1, 2, 2, 1, p), p),
            new Effect(Material.BROWN_TERRACOTTA, asl(4, 6, 0, 1, 2, 1, p), p),
            new Effect(Material.BROWN_TERRACOTTA, asl(2, 7, 0, 1, 3, 1, p), p),
            new Effect(Material.BROWN_TERRACOTTA, asl(1, 8, 0, 1, 1, 1, p), p),
            new Effect(Material.BROWN_TERRACOTTA, asl(3, 9, 1, 1, 1, 1, p), p),
            new Effect(Material.BROWN_TERRACOTTA, asl(-2, 4, 0, 1, 2, 1, p), p),
            new Effect(Material.BROWN_TERRACOTTA, asl(-4, 5, -1, 2, 2, 1, p), p),
            new Effect(Material.BROWN_TERRACOTTA, asl(-5, 6, 0, 1, 2, 1, p), p),
            new Effect(Material.BROWN_TERRACOTTA, asl(-3, 7, 0, 1, 3, 1, p), p),
            new Effect(Material.BROWN_TERRACOTTA, asl(-2, 8, 0, 1, 1, 1, p), p),
            new Effect(Material.BROWN_TERRACOTTA, asl(-4, 9, 1, 1, 1, 1, p), p),
    };

    static Effect[] wildG = {
            new Effect(Material.YELLOW_CONCRETE_POWDER, asl(1, 4, 0, 1, 2, 1, p), p),
            new Effect(Material.YELLOW_CONCRETE_POWDER, asl(2, 5, -1, 2, 2, 1, p), p),
            new Effect(Material.YELLOW_CONCRETE_POWDER, asl(4, 6, 0, 1, 2, 1, p), p),
            new Effect(Material.YELLOW_CONCRETE_POWDER, asl(2, 7, 0, 1, 3, 1, p), p),
            new Effect(Material.YELLOW_CONCRETE_POWDER, asl(1, 8, 0, 1, 1, 1, p), p),
            new Effect(Material.YELLOW_CONCRETE_POWDER, asl(3, 9, 1, 1, 1, 1, p), p),
            new Effect(Material.YELLOW_CONCRETE_POWDER, asl(-2, 4, 0, 1, 2, 1, p), p),
            new Effect(Material.YELLOW_CONCRETE_POWDER, asl(-4, 5, -1, 2, 2, 1, p), p),
            new Effect(Material.YELLOW_CONCRETE_POWDER, asl(-5, 6, 0, 1, 2, 1, p), p),
            new Effect(Material.YELLOW_CONCRETE_POWDER, asl(-3, 7, 0, 1, 3, 1, p), p),
            new Effect(Material.YELLOW_CONCRETE_POWDER, asl(-2, 8, 0, 1, 1, 1, p), p),
            new Effect(Material.YELLOW_CONCRETE_POWDER, asl(-4, 9, 1, 1, 1, 1, p), p),
    };

    static Effect[] wildO = {
            new Effect(Material.OBSIDIAN, asl(1, 4, 0, 1, 2, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(2, 5, -1, 2, 2, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(4, 6, 0, 1, 2, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(2, 7, 0, 1, 3, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(1, 8, 0, 1, 1, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(3, 9, 1, 1, 1, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(-2, 4, 0, 1, 2, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(-4, 5, -1, 2, 2, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(-5, 6, 0, 1, 2, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(-3, 7, 0, 1, 3, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(-2, 8, 0, 1, 1, 1, p), p),
            new Effect(Material.OBSIDIAN, asl(-4, 9, 1, 1, 1, 1, p), p),
    };

    static Effect[] tinyAntler = {
            new Effect(Material.GILDED_BLACKSTONE, asl(1, 4, 0, 1, 2, 1, p), p),
            new Effect(Material.GILDED_BLACKSTONE, asl(2, 5, -1, 1, 2, 1, p), p),
            new Effect(Material.BLACKSTONE_WALL, asl(2, 7, -1, 1, 1, 1, p), p),
            new Effect(Material.GILDED_BLACKSTONE, asl(-2, 4, 0, 1, 2, 1, p), p),
            new Effect(Material.GILDED_BLACKSTONE, asl(-3, 5, -1, 1, 2, 1, p), p),
            new Effect(Material.BLACKSTONE_WALL, asl(-3, 7, -1, 1, 1, 1, p), p),
    };


    static Effect[] warden = {
            new Effect(Material.CYAN_TERRACOTTA, asl(2, 2, -1, 2, 1, 1, p), p),
            new Effect(Material.CYAN_TERRACOTTA, asl(3, 3, -1, 1, 1, 1, p), p),
            new Effect(Material.CYAN_TERRACOTTA, asl(3, 4, -1, 2, 1, 1, p), p),
            new Effect(Material.BLACK_TERRACOTTA, asl(4, 5, 0, 1, 2, 1, p), p),
            new Effect(Material.BLACK_TERRACOTTA, asl(3, 6, 0, 1, 2, 1, p), p),
            new Effect(Material.BLACK_TERRACOTTA, asl(1, 7, 0, 2, 1, 1, p), p),
            new Effect(Material.BLACK_CONCRETE_POWDER, asl(1, 8, 0, 1, 1, 1, p), p),
            new Effect(Material.BLACK_CONCRETE_POWDER, asl(1, 6, 0, 1, 1, 1, p), p),
            new Effect(Material.BLACK_CONCRETE_POWDER, asl(3, 8, 0, 1, 1, 1, p), p),
            new Effect(Material.CYAN_TERRACOTTA, asl(-2, 2, -1, -2, 1, 1, p), p),
            new Effect(Material.CYAN_TERRACOTTA, asl(-3, 3, -1, -1, 1, 1, p), p),
            new Effect(Material.CYAN_TERRACOTTA, asl(-3, 4, -1, -2, 1, 1, p), p),
            new Effect(Material.BLACK_TERRACOTTA, asl(-4, 5, 0, -1, 2, 1, p), p),
            new Effect(Material.BLACK_TERRACOTTA, asl(-3, 6, 0, -1, 2, 1, p), p),
            new Effect(Material.BLACK_TERRACOTTA, asl(-1, 7, 0, -2, 1, 1, p), p),
            new Effect(Material.BLACK_CONCRETE_POWDER, asl(-1, 8, 0, -1, 1, 1, p), p),
            new Effect(Material.BLACK_CONCRETE_POWDER, asl(-1, 6, 0, -1, 1, 1, p), p),
            new Effect(Material.BLACK_CONCRETE_POWDER, asl(-3, 8, 0, -1, 1, 1, p), p),
    };

    static Effect[] angel = {
            new Effect(Material.GLOWSTONE, asl(2, 6, 1, -4, 1, 1, p), p),
            new Effect(Material.GLOWSTONE, asl(2, 6, -2, -4, 1, 1, p), p),
            new Effect(Material.GLOWSTONE, asl(-2, 6, 1, 1, 1, -2, p), p),
            new Effect(Material.GLOWSTONE, asl(1, 6, 1, 1, 1, -2, p), p),
    };

    static Effect[] god = {
            new Effect(Material.OCHRE_FROGLIGHT, asl(4, 6, -2, -1, 1, -2, p), p),
            new Effect(Material.OCHRE_FROGLIGHT, asl(3, 6, -3, -1, 1, -1, p), p),
            new Effect(Material.OCHRE_FROGLIGHT, asl(3, 6, -4, -2, 1, -1, p), p),
            new Effect(Material.OCHRE_FROGLIGHT, asl(-3, 6, -2, -1, 1, -2, p), p),
            new Effect(Material.OCHRE_FROGLIGHT, asl(-2, 6, -3, -1, 1, -1, p), p),
            new Effect(Material.OCHRE_FROGLIGHT, asl(-1, 6, -4, -2, 1, -1, p), p),
            new Effect(Material.OCHRE_FROGLIGHT, asl(-3, 6, 2, -1, 1, -2, p), p),
            new Effect(Material.OCHRE_FROGLIGHT, asl(-2, 6, 2, -1, 1, -1, p), p),
            new Effect(Material.OCHRE_FROGLIGHT, asl(-1, 6, 3, -2, 1, -1, p), p),
            new Effect(Material.OCHRE_FROGLIGHT, asl(4, 6, 2, -1, 1, -2, p), p),
            new Effect(Material.OCHRE_FROGLIGHT, asl(3, 6, 2, -1, 1, -1, p), p),
            new Effect(Material.OCHRE_FROGLIGHT, asl(3, 6, 3, -2, 1, -1, p), p),
    };

    static Effect[] catBlack = {
            new Effect(Material.GOLD_BLOCK, asl(1, 4, 1, 2, 1, 2, p), p),
            new Effect(Material.GOLD_BLOCK, asl(2, 3, 0, 1, 1, 2, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-3, 4, 1, 2, 1, 2, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-3, 3, 0, 1, 1, 2, p), p),
    };

    static Effect[] crown = {
            new Effect(Material.GOLD_BLOCK, asl(-1, 4, -2, 2, 1, 4, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-2, 4, -1, 4, 1, 2, p), p),
            new Effect(Material.GOLD_BLOCK, asl(0, 5, -2, 1, 1, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-2, 5, -1, 1, 1, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(1, 5, 0, 1, 1, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-1, 5, 1, 1, 1, 1, p), p),
    };

    static Effect[] hugeCrown = {
            new Effect(Material.GOLD_BLOCK, asl(-2, 4, -2, 4, 1, 4, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-3, 5, -2, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-2, 5, -3, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(1, 5, -3, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(2, 5, -2, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-3, 5, 1, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-2, 5, 2, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(2, 5, 1, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(1, 5, 2, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(1, 7, 1, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(1, 7, -2, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-2, 7, 1, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-2, 7, -2, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-1, 7, -1, 2, 2, 2, p), p),
    };

    static Effect[] hugeCrown2 = {
            new Effect(Material.GOLD_BLOCK, asl(-2, 4, -2, 4, 1, 4, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-3, 5, -2, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-2, 5, -3, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(1, 5, -3, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(2, 5, -2, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-3, 5, 1, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-2, 5, 2, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(2, 5, 1, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(1, 5, 2, 1, 2, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(2, 6, 2, 1, 1, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(2, 6, -3, 1, 1, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-3, 6, 2, 1, 1, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-3, 6, -3, 1, 1, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(1, 7, 1, 1, 1, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(1, 7, -2, 1, 1, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-2, 7, 1, 1, 1, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(1, 7, -2, 1, 1, 1, p), p),
            new Effect(Material.GOLD_BLOCK, asl(-1, 7, -1, 2, 1, 2, p), p),
            new Effect(Material.HONEY_BLOCK, asl(-1, 5, -1, 2, 2, 2, p), p),
    };

    static Effect[] test = {
            new Effect(Material.GOLD_BLOCK, asl(0, 4, 0, 1, 1, 1, p), p),
            new Effect(Material.IRON_BLOCK, asl(1, 4, 0, 1, 1, 1, p), p),
            new Effect(Material.IRON_BLOCK, asl(2, 4, 2, 1, 1, 1, p), p),
            new Effect(Material.IRON_BLOCK, asl(2, 0, 2, 1, 1, 1, p), p),
            new Effect(Material.IRON_BLOCK, asl(-3, 0, -3, 1, 1, 1, p), p),
            new Effect(Material.IRON_BLOCK, asl(-3, 4, -3, 1, 1, 1, p), p)
    };

    static Effect[] Dragon;
    static Effect[] Tiger;

    static {
        float cx = 0f;
        float cy = 0f;
        float cz = 1;
        Material black = Material.BLACK_WOOL;
        Material brown = Material.BLACK_TERRACOTTA;
        Material white = Material.SMOOTH_QUARTZ;
        Material goldBlock = Material.GOLD_BLOCK;
        Material lightBrown = Material.YELLOW_GLAZED_TERRACOTTA;
        Dragon = new Effect[]{
                new Effect(brown, asl(cx - 2, cy - 1, cz + 4, 4, 2, 1, hp), hp),
                new Effect(brown, asl(cx - 1, cy - 2, cz + 4, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 2, cy - 2, cz + 3, 4, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 3, cy - 1, cz + 3, 1, 2, 1, hp), hp),
                new Effect(brown, asl(cx - 5, cy, cz + 2, 2, 2, 1, hp), hp),
                new Effect(brown, asl(cx - 4, cy - 1, cz + 2, 1, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 4, cy + 1, cz + 3, 1, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 2, cy - 1, cz + 3, 1, 2, 1, hp), hp),
                new Effect(brown, asl(cx + 3, cy, cz + 2, 2, 2, 1, hp), hp),
                new Effect(brown, asl(cx + 3, cy - 1, cz + 2, 1, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 3, cy + 1, cz + 3, 1, 1, 1, hp), hp),
                new Effect(white, asl(cx + 1.9f, cy, cz + 5, 1.2f, 1.2f, 1.2f, hp), hp),
                new Effect(white, asl(cx - 3.1f, cy, cz + 5, 1.2f, 1.2f, 1.2f, hp), hp),
                new Effect(white, asl(cx - 4.1f, cy + 2, cz + 3, 8.2f, 1.2f, 1.2f, hp), hp),
                new Effect(brown, asl(cx - 3, cy + 1, cz + 4, 2, 1, 2, hp), hp),
                new Effect(brown, asl(cx + 1, cy + 1, cz + 4, 2, 1, 2, hp), hp),
                new Effect(black, asl(cx - 1, cy + 1, cz + 3, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 1, cy + 2, cz + 4, 2, 3, 2.1f, hp), hp),
                new Effect(black, asl(cx - 2, cy + 2, cz + 5, 4, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 3, cy + 2, cz + 4, 1, 1, 2, hp), hp),
                new Effect(brown, asl(cx - 2, cy + 4, cz + 4, 1, 1, 2, hp), hp),
                new Effect(brown, asl(cx + 2, cy + 2, cz + 4, 1, 1, 2, hp), hp),
                new Effect(brown, asl(cx + 1, cy + 4, cz + 4, 1, 1, 2, hp), hp),
                new Effect(brown, asl(cx - 4, cy + 3, cz + 4, 3, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 5, cy + 5, cz + 2, 2, 2, 1, hp), hp),
                new Effect(brown, asl(cx - 6, cy + 2, cz + 2, 2, 3, 1, hp), hp),
                new Effect(lightBrown, asl(cx - 6.1f, cy + 3, cz + 2, 1.2f, 1.2f, 1.2f, hp), hp),
                new Effect(lightBrown, asl(cx - 5.1f, cy + 4, cz + 3, 1.2f, 1.2f, 1.2f, hp), hp),
                new Effect(brown, asl(cx - 5f, cy + 2, cz + 3, 1, 2, 1, hp), hp),
                new Effect(brown, asl(cx - 6, cy, cz + 1, 1, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 8, cy + 1, cz + 1, 3, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 7, cy + 2, cz + 1, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 1, cy + 3, cz + 4, 3, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 3, cy + 5, cz + 2, 2, 2, 1, hp), hp),
                new Effect(brown, asl(cx + 4, cy + 2, cz + 2, 2, 3, 1, hp), hp),
                new Effect(lightBrown, asl(cx + 4.9f, cy + 3, cz + 2, 1.2f, 1.2f, 1.2f, hp), hp),
                new Effect(lightBrown, asl(cx + 3.9f, cy + 4, cz + 3, 1.2f, 1.2f, 1.2f, hp), hp),
                new Effect(brown, asl(cx + 4f, cy + 2, cz + 3, 1, 2, 1, hp), hp),
                new Effect(brown, asl(cx + 5, cy, cz + 1, 1, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 5, cy + 1, cz + 1, 3, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 5, cy + 2, cz + 1, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 4, cy + 4, cz + 3, 8, 2, 1, hp), hp),
                new Effect(brown, asl(cx - 1, cy + 6, cz + 3, 2, 3, 2, hp), hp),
                new Effect(goldBlock, asl(cx - 2.1f, cy + 6, cz + 3, 4.2f, 1, 1.1f, hp), hp),
                new Effect(white, asl(cx - 3, cy + 6, cz + 3, 6, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 5, cy + 8, cz + 1, 10, 1, 2, hp), hp),
                new Effect(brown, asl(cx - 6, cy + 7, cz + 2, 1, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 5, cy + 7, cz + 3, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 3, cy + 7, cz + 4, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 3, cy + 8, cz + 3, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 5, cy + 7, cz + 2, 1, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 3, cy + 7, cz + 3, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 1, cy + 7, cz + 4, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 1, cy + 8, cz + 3, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 8, cy + 4, cz + 1, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 7, cy + 5, cz + 1, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 6, cy + 6, cz + 1, 1, 2, 1, hp), hp),
                new Effect(brown, asl(cx - 6, cy + 8, cz - 1, 2, 1, 2, hp), hp),
                new Effect(brown, asl(cx + 6, cy + 4, cz + 1, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 5, cy + 5, cz + 1, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 5, cy + 6, cz + 1, 1, 2, 1, hp), hp),
                new Effect(brown, asl(cx + 4, cy + 8, cz - 1, 2, 1, 2, hp), hp),
                new Effect(brown, asl(cx - 4, cy + 9, cz + 1, 8, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 1, cy + 9, cz + 2, 2, 1, 1, hp), hp),
                new Effect(brown, asl(cx - 4, cy + 10, cz + 1, 1, 2, 1, hp), hp),
                new Effect(brown, asl(cx - 3, cy + 10, cz, 1, 2, 1, hp), hp),
                new Effect(brown, asl(cx - 4, cy + 11, cz, 1, 2, 1, hp), hp),
                new Effect(brown, asl(cx - 5, cy + 12, cz, 1, 3, 1, hp), hp),
                new Effect(brown, asl(cx - 4, cy + 15, cz, 1, 1, 1, hp), hp),
                new Effect(brown, asl(cx + 3, cy + 10, cz + 1, 1, 2, 1, hp), hp),
                new Effect(brown, asl(cx + 2, cy + 10, cz, 1, 2, 1, hp), hp),
                new Effect(brown, asl(cx + 3, cy + 11, cz, 1, 2, 1, hp), hp),
                new Effect(brown, asl(cx + 4, cy + 12, cz, 1, 3, 1, hp), hp),
                new Effect(brown, asl(cx + 3, cy + 15, cz, 1, 1, 1, hp), hp),
                new Effect(brown, asl(-3, 0, -3, 6, 5, 5, p), p)
        };

        float c1x = 0, c1y = -1, c1z = 1;
        Material mouth = Material.GRAY_CONCRETE;
        Material yellow = Material.YELLOW_WOOL;
        Tiger = new Effect[]{
                new Effect(white, asl(c1x - 3, c1y - 2, c1z + 2, 6, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 2, c1y - 2, c1z + 3, 4, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 4, c1y - 1, c1z + 2, 8, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 3, c1y - 1, c1z + 3, 6, 1, 2, hp), hp),
                new Effect(white, asl(c1x - 1, c1y - 1, c1z + 5, 2, 1, 1, hp), hp),
                new Effect(mouth, asl(c1x - 2, c1y - 1, c1z + 5, 1, 1, 1, hp), hp),
                new Effect(mouth, asl(c1x + 1, c1y - 1, c1z + 5, 1, 1, 1, hp), hp),
                new Effect(mouth, asl(c1x - 1, c1y, c1z + 5, 2, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 1, c1y + 1, c1z + 5, 2, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 2, c1y, c1z + 5, 1, 4, 1, hp), hp),
                new Effect(white, asl(c1x + 1, c1y, c1z + 5, 1, 4, 1, hp), hp),
                new Effect(white, asl(c1x - 1, c1y + 2, c1z + 6, 2, 2, 1, hp), hp),
                new Effect(white, asl(c1x - 3, c1y + 2, c1z + 5, 4, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 3, c1y + 1, c1z + 4, 6, 4, 1, hp), hp),
                new Effect(black, asl(c1x - 3, c1y, c1z + 4, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 5, c1y + 1, c1z + 3, 2, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 4, c1y, c1z + 3, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 5, c1y, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 6, c1y + 1, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 7, c1y + 2, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 6, c1y, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 7, c1y + 1, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 8, c1y + 2, c1z + 2, 1, 4, 1, hp), hp),
                new Effect(black, asl(c1x + 2, c1y, c1z + 4, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 3, c1y + 1, c1z + 3, 2, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 3, c1y, c1z + 3, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x + 4, c1y, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x + 5, c1y + 1, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x + 6, c1y + 2, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 5, c1y, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 6, c1y + 1, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 7, c1y + 2, c1z + 2, 1, 4, 1, hp), hp),
                new Effect(black, asl(c1x - 5, c1y + 2, c1z + 3, 2, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 6, c1y + 2, c1z + 3, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 4, c1y + 3, c1z + 4, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 5, c1y + 3, c1z + 3, 2, 2, 1, hp), hp),
                new Effect(black, asl(c1x - 6, c1y + 3, c1z + 3, 1, 2, 1, hp), hp),
                new Effect(white, asl(c1x - 7, c1y + 3, c1z + 3, 1, 2, 1, hp), hp),
                new Effect(black, asl(c1x + 3, c1y + 2, c1z + 3, 2, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 5, c1y + 2, c1z + 3, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 3, c1y + 3, c1z + 4, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 3, c1y + 3, c1z + 3, 2, 2, 1, hp), hp),
                new Effect(black, asl(c1x + 5, c1y + 3, c1z + 3, 1, 2, 1, hp), hp),
                new Effect(white, asl(c1x + 6, c1y + 3, c1z + 3, 1, 2, 1, hp), hp),
                new Effect(white, asl(c1x - 4, c1y + 5, c1z + 3, 1, 1, 1, hp), hp),
                new Effect(yellow, asl(c1x - 4, c1y + 6, c1z + 3, 1, 1, 1, hp), hp),
                new Effect(yellow, asl(c1x - 3, c1y + 6, c1z + 4, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 2, c1y + 7, c1z + 4, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 5, c1y + 5, c1z + 3, 1, 2, 1, hp), hp),
                new Effect(white, asl(c1x - 6, c1y + 5, c1z + 3, 1, 2, 1, hp), hp),
                new Effect(white, asl(c1x + 3, c1y + 5, c1z + 3, 1, 1, 1, hp), hp),
                new Effect(yellow, asl(c1x + 3, c1y + 6, c1z + 3, 1, 1, 1, hp), hp),
                new Effect(yellow, asl(c1x + 2, c1y + 6, c1z + 4, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 1, c1y + 7, c1z + 4, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x + 4, c1y + 5, c1z + 3, 1, 2, 1, hp), hp),
                new Effect(white, asl(c1x + 5, c1y + 5, c1z + 3, 1, 2, 1, hp), hp),
                new Effect(goldBlock, asl(c1x - 3, c1y + 5, c1z + 4, 6, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 1, c1y + 4, c1z + 5, 2, 2, 1, hp), hp),
                new Effect(white, asl(c1x - 1, c1y + 6, c1z + 4, 2, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 2, c1y + 5, c1z + 5, 1, 2, 1, hp), hp),
                new Effect(white, asl(c1x + 1, c1y + 5, c1z + 5, 1, 2, 1, hp), hp),
                new Effect(black, asl(c1x - 6, c1y + 9, c1z + 2, 12, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 1, c1y + 7, c1z + 3, 2, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 1, c1y + 10, c1z + 2, 2, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 1, c1y + 8, c1z + 3, 2, 2, 1, hp), hp),
                new Effect(black, asl(c1x - 4, c1y + 7, c1z + 3, 1, 2, 1, hp), hp),
                new Effect(white, asl(c1x - 5, c1y + 7, c1z + 3, 1, 2, 1, hp), hp),
                new Effect(black, asl(c1x - 3, c1y + 7, c1z + 4, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 2, c1y + 8, c1z + 4, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 2, c1y + 9, c1z + 3, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 3, c1y + 8, c1z + 3, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 4, c1y + 9, c1z + 3, 2, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 4, c1y + 10, c1z + 2, 3, 1, 1, hp), hp),
                new Effect(black, asl(c1x + 3, c1y + 7, c1z + 3, 1, 2, 1, hp), hp),
                new Effect(white, asl(c1x + 4, c1y + 7, c1z + 3, 1, 2, 1, hp), hp),
                new Effect(black, asl(c1x + 2, c1y + 7, c1z + 4, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x + 1, c1y + 8, c1z + 4, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x + 1, c1y + 9, c1z + 3, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 2, c1y + 8, c1z + 3, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 2, c1y + 9, c1z + 3, 2, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 1, c1y + 10, c1z + 2, 3, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 7, c1y + 5, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 8, c1y + 6, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 7, c1y + 7, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 6, c1y + 8, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 7, c1y + 6, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 6, c1y + 7, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 7, c1y + 8, c1z + 2, 1, 2, 1, hp), hp),
                new Effect(black, asl(c1x + 6, c1y + 5, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x + 7, c1y + 6, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x + 6, c1y + 7, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x + 5, c1y + 8, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 6, c1y + 6, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 5, c1y + 7, c1z + 2, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 6, c1y + 8, c1z + 2, 1, 2, 1, hp), hp),
                new Effect(white, asl(c1x - 6, c1y + 10, c1z, 3, 1, 2, hp), hp),
                new Effect(white, asl(c1x - 7, c1y + 11, c1z, 5, 1, 2, hp), hp),
                new Effect(white, asl(c1x - 6, c1y + 13, c1z, 2, 1, 2, hp), hp),
                new Effect(black, asl(c1x - 5, c1y + 11, c1z + 1, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x - 6, c1y + 12, c1z + 1, 2, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 7, c1y + 12, c1z + 1, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 4, c1y + 12, c1z + 1, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x - 7, c1y + 12, c1z, 4, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 3, c1y + 10, c1z, 3, 1, 2, hp), hp),
                new Effect(white, asl(c1x + 2, c1y + 11, c1z, 5, 1, 2, hp), hp),
                new Effect(white, asl(c1x + 4, c1y + 13, c1z, 2, 1, 2, hp), hp),
                new Effect(black, asl(c1x + 4, c1y + 11, c1z + 1, 1, 1, 1, hp), hp),
                new Effect(black, asl(c1x + 4, c1y + 12, c1z + 1, 2, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 3, c1y + 12, c1z + 1, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 3, c1y + 12, c1z + 1, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 6, c1y + 12, c1z + 1, 1, 1, 1, hp), hp),
                new Effect(white, asl(c1x + 3, c1y + 12, c1z, 4, 1, 1, hp), hp),
                new Effect(white, asl(-3, 0, -3, 6, 5, 5, p), p)
        };
    }

    static Effect[] cyanLoong;

    static Effect[] darkLoong;

    static {
        float tx = -8;
        float ty = p;
        float tz = -6;
        cyanLoong = new Effect[]{
                new Effect(Material.DARK_PRISMARINE_SLAB, asl(tx + 0, ty + 2, tz + 12, 1, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 1, ty + 1, tz + 4, 2, 4, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 1, ty + 1, tz + 14, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 1, ty + 2, tz + 6, 1, 2, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 1, ty + 5, tz + 4, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 2, ty + 0, tz + 3, 2, 1, 3, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 2, ty + 1, tz + 3, 1, 6, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 2, ty + 1, tz + 6, 1, 1, 2, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 2, ty + 2, tz + 6, 1, 2, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE_SLAB, asl(tx + 2, ty + 2, tz + 14, 1, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 2, ty + 3, tz + 8, 3, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 2, ty + 4, tz + 6, 1, 1, 3, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 2, ty + 5, tz + 5, 1, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 2, ty + 5, tz + 6, 1, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 2, ty + 6, tz + 4, 2, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 2, ty + 6, tz + 6, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 3, ty + 0, tz + 1, 2, 2, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 3, ty + 0, tz + 6, 1, 1, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 3, ty + 1, tz + 8, 2, 2, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 3, ty + 2, tz + 2, 10, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 3, ty + 2, tz + 9, 2, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE_SLAB, asl(tx + 3, ty + 2, tz + 15, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 3, ty + 3, tz + 2, 2, 3, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 3, ty + 3, tz + 9, 1, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 3, ty + 4, tz + 7, 1, 3, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 3, ty + 5, tz + 9, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 3, ty + 6, tz + 2, 1, 1, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 3, ty + 6, tz + 5, 1, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 3, ty + 11, tz + 6, 1, 2, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 3, ty + 13, tz + 6, 1, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 4, ty + 0, tz + 3, 8, 1, 5, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 4, ty + 1, tz + 9, 1, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 4, ty + 2, tz + 10, 1, 2, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 4, ty + 2, tz + 11, 8, 2, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 4, ty + 3, tz + 1, 2, 4, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 4, ty + 3, tz + 9, 1, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 4, ty + 4, tz + 8, 1, 4, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 4, ty + 4, tz + 10, 1, 2, 1, hp), hp),
                new Effect(Material.YELLOW_WOOL, asl(tx + 4, ty + 4, tz + 11, 1, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 4, ty + 6, tz + 9, 1, 1, 2, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 4, ty + 6, tz + 11, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 4, ty + 7, tz + 2, 8, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 4, ty + 7, tz + 4, 1, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 4, ty + 7, tz + 5, 8, 1, 3, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 4, ty + 7, tz + 9, 8, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 4, ty + 9, tz + 7, 2, 1, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 4, ty + 10, tz + 7, 1, 1, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 4, ty + 11, tz + 7, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 5, ty + 0, tz + 2, 8, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 5, ty + 0, tz + 8, 7, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 5, ty + 0, tz + 9, 6, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 5, ty + 1, tz + 10, 6, 1, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 5, ty + 1, tz + 15, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 5, ty + 2, tz + 0, 2, 3, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 5, ty + 2, tz + 1, 1, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 5, ty + 2, tz + 10, 6, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 5, ty + 2, tz + 12, 6, 2, 1, hp), hp),
                new Effect(Material.GOLD_BLOCK, asl(tx + 5, ty + 4, tz + 12, 6, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 5, ty + 5, tz + 0, 1, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 5, ty + 5, tz + 11, 6, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 5, ty + 5, tz + 12, 1, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 5, ty + 6, tz + 11, 6, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 5, ty + 7, tz + 1, 1, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 5, ty + 7, tz + 4, 2, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 5, ty + 7, tz + 8, 7, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 5, ty + 7, tz + 10, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 5, ty + 8, tz + 2, 6, 1, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 5, ty + 8, tz + 7, 1, 1, 3, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 6, ty + 0, tz + 10, 4, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 6, ty + 1, tz + 0, 1, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 6, ty + 1, tz + 12, 4, 1, 3, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 6, ty + 2, tz + 13, 4, 1, 3, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 6, ty + 2, tz + 16, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 6, ty + 3, tz + 2, 4, 4, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 6, ty + 3, tz + 13, 4, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 6, ty + 3, tz + 14, 1, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 6, ty + 4, tz + 13, 1, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 6, ty + 5, tz + 12, 1, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 6, ty + 6, tz + 12, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 6, ty + 8, tz + 4, 4, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 6, ty + 8, tz + 8, 1, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 6, ty + 9, tz + 3, 4, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 7, ty + 0, tz + 1, 2, 4, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 7, ty + 0, tz + 11, 3, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 7, ty + 0, tz + 13, 2, 1, 3, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 7, ty + 0, tz + 16, 2, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 7, ty + 1, tz + 15, 2, 1, 2, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 7, ty + 1, tz + 17, 2, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 7, ty + 2, tz + 16, 2, 1, 2, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 7, ty + 3, tz + 14, 2, 1, 2, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 7, ty + 4, tz + 13, 2, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 7, ty + 5, tz + 1, 2, 3, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 7, ty + 5, tz + 12, 2, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 7, ty + 6, tz + 10, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 7, ty + 7, tz + 4, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 7, ty + 8, tz + 5, 2, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 7, ty + 9, tz + 2, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 7, ty + 9, tz + 4, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 9, ty + 1, tz + 0, 1, 4, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 9, ty + 1, tz + 15, 2, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 9, ty + 2, tz + 16, 1, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 9, ty + 3, tz + 14, 1, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 9, ty + 4, tz + 13, 1, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 9, ty + 5, tz + 12, 2, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 9, ty + 6, tz + 12, 1, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 9, ty + 7, tz + 4, 2, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 9, ty + 7, tz + 10, 2, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 9, ty + 8, tz + 8, 2, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 10, ty + 2, tz + 0, 1, 4, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 10, ty + 6, tz + 1, 2, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 10, ty + 8, tz + 7, 1, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 10, ty + 9, tz + 8, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 11, ty + 0, tz + 1, 2, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 11, ty + 1, tz + 8, 2, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 11, ty + 1, tz + 9, 1, 6, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 11, ty + 2, tz + 10, 1, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE_SLAB, asl(tx + 11, ty + 2, tz + 15, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 11, ty + 3, tz + 1, 1, 3, 2, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 11, ty + 3, tz + 8, 3, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 11, ty + 4, tz + 8, 3, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 11, ty + 4, tz + 10, 1, 2, 1, hp), hp),
                new Effect(Material.YELLOW_WOOL, asl(tx + 11, ty + 4, tz + 11, 1, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 11, ty + 5, tz + 8, 2, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 11, ty + 6, tz + 10, 1, 1, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE_POWDER, asl(tx + 11, ty + 6, tz + 11, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 11, ty + 7, tz + 4, 1, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 11, ty + 9, tz + 7, 1, 3, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 11, ty + 10, tz + 8, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 12, ty + 0, tz + 3, 2, 1, 3, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 12, ty + 0, tz + 6, 1, 1, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 12, ty + 1, tz + 3, 1, 1, 5, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 12, ty + 2, tz + 9, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 12, ty + 3, tz + 2, 1, 4, 1, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 12, ty + 3, tz + 9, 1, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 12, ty + 4, tz + 7, 2, 2, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 12, ty + 5, tz + 9, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 12, ty + 6, tz + 3, 2, 1, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 12, ty + 6, tz + 5, 1, 1, 3, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 12, ty + 11, tz + 6, 1, 2, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 12, ty + 13, tz + 6, 1, 2, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 13, ty + 1, tz + 3, 1, 1, 5, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 13, ty + 2, tz + 3, 1, 4, 3, hp), hp),
                new Effect(Material.CYAN_CONCRETE, asl(tx + 13, ty + 2, tz + 6, 1, 2, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE_SLAB, asl(tx + 13, ty + 2, tz + 14, 1, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 13, ty + 4, tz + 6, 1, 3, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 13, ty + 6, tz + 5, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 14, ty + 1, tz + 4, 1, 4, 2, hp), hp),
                new Effect(Material.DARK_PRISMARINE, asl(tx + 14, ty + 1, tz + 14, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 14, ty + 2, tz + 6, 1, 2, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 14, ty + 5, tz + 4, 1, 1, 1, hp), hp),
                new Effect(Material.DARK_PRISMARINE_SLAB, asl(tx + 15, ty + 2, tz + 12, 1, 1, 2, hp), hp),
        };

        darkLoong = new Effect[]{
                new Effect(Material.POLISHED_BLACKSTONE_PRESSURE_PLATE, asl(tx + 0, ty + 3, tz + 12, 1, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 1, ty + 2, tz + 4, 2, 4, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 1, ty + 2, tz + 14, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 1, ty + 3, tz + 6, 1, 2, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 1, ty + 6, tz + 4, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 2, ty + 1, tz + 3, 2, 1, 3, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 2, ty + 2, tz + 3, 1, 6, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 2, ty + 2, tz + 6, 1, 1, 2, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 2, ty + 3, tz + 6, 1, 2, 2, hp), hp),
                new Effect(Material.POLISHED_BLACKSTONE_PRESSURE_PLATE, asl(tx + 2, ty + 3, tz + 14, 1, 1, 1, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 2, ty + 4, tz + 8, 3, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 2, ty + 5, tz + 6, 1, 1, 3, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 2, ty + 6, tz + 5, 1, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 2, ty + 6, tz + 6, 1, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 2, ty + 7, tz + 4, 2, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 2, ty + 7, tz + 6, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 3, ty + 1, tz + 1, 2, 2, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 3, ty + 1, tz + 6, 1, 1, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 3, ty + 2, tz + 8, 2, 2, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 3, ty + 3, tz + 2, 10, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 3, ty + 3, tz + 9, 2, 1, 1, hp), hp),
                new Effect(Material.POLISHED_BLACKSTONE_PRESSURE_PLATE, asl(tx + 3, ty + 3, tz + 15, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 3, ty + 4, tz + 2, 2, 3, 1, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 3, ty + 4, tz + 9, 1, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 3, ty + 5, tz + 7, 1, 3, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 3, ty + 6, tz + 9, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 3, ty + 7, tz + 2, 1, 1, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 3, ty + 7, tz + 5, 1, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 3, ty + 12, tz + 6, 1, 2, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 3, ty + 14, tz + 6, 1, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 4, ty + 1, tz + 3, 8, 1, 5, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 4, ty + 2, tz + 9, 1, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 4, ty + 3, tz + 10, 1, 2, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 4, ty + 3, tz + 11, 8, 2, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 4, ty + 4, tz + 1, 2, 4, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 4, ty + 4, tz + 9, 1, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 4, ty + 5, tz + 8, 1, 4, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 4, ty + 5, tz + 10, 1, 2, 1, hp), hp),
                new Effect(Material.YELLOW_WOOL, asl(tx + 4, ty + 5, tz + 11, 1, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 4, ty + 7, tz + 9, 1, 1, 2, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 4, ty + 7, tz + 11, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 4, ty + 8, tz + 2, 8, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 4, ty + 8, tz + 4, 1, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 4, ty + 8, tz + 5, 8, 1, 3, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 4, ty + 8, tz + 9, 8, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 4, ty + 10, tz + 7, 2, 1, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 4, ty + 11, tz + 7, 1, 1, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 4, ty + 12, tz + 7, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 5, ty + 1, tz + 2, 8, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 5, ty + 1, tz + 8, 7, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 5, ty + 1, tz + 9, 6, 1, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 5, ty + 2, tz + 10, 6, 1, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 5, ty + 2, tz + 15, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 5, ty + 3, tz + 0, 2, 3, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 5, ty + 3, tz + 1, 1, 1, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 5, ty + 3, tz + 10, 6, 1, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 5, ty + 3, tz + 12, 6, 2, 1, hp), hp),
                new Effect(Material.GOLD_BLOCK, asl(tx + 5, ty + 5, tz + 12, 6, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 5, ty + 6, tz + 0, 1, 1, 1, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 5, ty + 6, tz + 11, 6, 1, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 5, ty + 6, tz + 12, 1, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 5, ty + 7, tz + 11, 6, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 5, ty + 8, tz + 1, 1, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 5, ty + 8, tz + 4, 2, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 5, ty + 8, tz + 8, 7, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 5, ty + 8, tz + 10, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 5, ty + 9, tz + 2, 6, 1, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 5, ty + 9, tz + 7, 1, 1, 3, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 6, ty + 1, tz + 10, 4, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 6, ty + 2, tz + 0, 1, 1, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 6, ty + 2, tz + 12, 4, 1, 3, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 6, ty + 3, tz + 13, 4, 1, 3, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 6, ty + 3, tz + 16, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 6, ty + 4, tz + 2, 4, 4, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 6, ty + 4, tz + 13, 4, 1, 1, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 6, ty + 4, tz + 14, 1, 1, 1, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 6, ty + 5, tz + 13, 1, 1, 1, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 6, ty + 6, tz + 12, 1, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 6, ty + 7, tz + 12, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 6, ty + 9, tz + 4, 4, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 6, ty + 9, tz + 8, 1, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 6, ty + 10, tz + 3, 4, 1, 1, hp), hp),
                new Effect(Material.BLACK_WOOL, asl(tx + 7, ty + 0, tz + 14, 2, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 7, ty + 1, tz + 1, 2, 4, 1, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 7, ty + 1, tz + 11, 3, 1, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 7, ty + 1, tz + 13, 2, 1, 3, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 7, ty + 1, tz + 16, 2, 1, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 7, ty + 2, tz + 15, 2, 1, 2, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 7, ty + 2, tz + 17, 2, 1, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 7, ty + 3, tz + 16, 2, 1, 2, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 7, ty + 4, tz + 14, 2, 1, 2, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 7, ty + 5, tz + 13, 2, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 7, ty + 6, tz + 1, 2, 3, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 7, ty + 6, tz + 12, 2, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 7, ty + 7, tz + 10, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 7, ty + 8, tz + 4, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 7, ty + 9, tz + 5, 2, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 7, ty + 10, tz + 2, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 7, ty + 10, tz + 4, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 9, ty + 2, tz + 0, 1, 4, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 9, ty + 2, tz + 15, 2, 1, 1, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 9, ty + 3, tz + 16, 1, 1, 1, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 9, ty + 4, tz + 14, 1, 1, 1, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 9, ty + 5, tz + 13, 1, 1, 1, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 9, ty + 6, tz + 12, 2, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 9, ty + 7, tz + 12, 1, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 9, ty + 8, tz + 4, 2, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 9, ty + 8, tz + 10, 2, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 9, ty + 9, tz + 8, 2, 1, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 10, ty + 3, tz + 0, 1, 4, 2, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 10, ty + 7, tz + 1, 2, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 10, ty + 9, tz + 7, 1, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 10, ty + 10, tz + 8, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 11, ty + 1, tz + 1, 2, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 11, ty + 2, tz + 8, 2, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 11, ty + 2, tz + 9, 1, 6, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 11, ty + 3, tz + 10, 1, 2, 1, hp), hp),
                new Effect(Material.POLISHED_BLACKSTONE_PRESSURE_PLATE, asl(tx + 11, ty + 3, tz + 15, 2, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 11, ty + 4, tz + 1, 1, 3, 2, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 11, ty + 4, tz + 8, 3, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 11, ty + 5, tz + 8, 3, 1, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 11, ty + 5, tz + 10, 1, 2, 1, hp), hp),
                new Effect(Material.YELLOW_WOOL, asl(tx + 11, ty + 5, tz + 11, 1, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 11, ty + 6, tz + 8, 2, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 11, ty + 7, tz + 10, 1, 1, 1, hp), hp),
                new Effect(Material.BLACK_CONCRETE_POWDER, asl(tx + 11, ty + 7, tz + 11, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 11, ty + 8, tz + 4, 1, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 11, ty + 10, tz + 7, 1, 3, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 11, ty + 11, tz + 8, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 12, ty + 1, tz + 3, 2, 1, 3, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 12, ty + 1, tz + 6, 1, 1, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 12, ty + 2, tz + 3, 1, 1, 5, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 12, ty + 3, tz + 9, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 12, ty + 4, tz + 2, 1, 4, 1, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 12, ty + 4, tz + 9, 1, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 12, ty + 5, tz + 7, 2, 2, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 12, ty + 6, tz + 9, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 12, ty + 7, tz + 3, 2, 1, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 12, ty + 7, tz + 5, 1, 1, 3, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 12, ty + 12, tz + 6, 1, 2, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 12, ty + 14, tz + 6, 1, 2, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 13, ty + 2, tz + 3, 1, 1, 5, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 13, ty + 3, tz + 3, 1, 4, 3, hp), hp),
                new Effect(Material.BLACK_SHULKER_BOX, asl(tx + 13, ty + 3, tz + 6, 1, 2, 2, hp), hp),
                new Effect(Material.POLISHED_BLACKSTONE_PRESSURE_PLATE, asl(tx + 13, ty + 3, tz + 14, 1, 1, 1, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 13, ty + 5, tz + 6, 1, 3, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 13, ty + 7, tz + 5, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 14, ty + 2, tz + 4, 1, 4, 2, hp), hp),
                new Effect(Material.BLACKSTONE, asl(tx + 14, ty + 2, tz + 14, 1, 1, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 14, ty + 3, tz + 6, 1, 2, 1, hp), hp),
                new Effect(Material.LIGHT_GRAY_WOOL, asl(tx + 14, ty + 6, tz + 4, 1, 1, 1, hp), hp),
                new Effect(Material.POLISHED_BLACKSTONE_PRESSURE_PLATE, asl(tx + 15, ty + 3, tz + 12, 1, 1, 2, hp), hp),
        };
    }

    public static Transformation asl(float x, float y, float z, float sx, float sy, float sz, float scale) {
        return new Transformation(
                new Vector3f(x * scale, y * scale, z * scale),
                new Quaternionf(),
                new Vector3f(sx * scale, sy * scale, sz * scale),
                new Quaternionf()
        );
    }
}
